global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'flask-app'
    static_configs:
      - targets: ['petlove-case-flask:5000']